### ISSUE TITLE
Dependency installation fails in GitHub build

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/xpack-dnanexus#25]
Some deps installation fails in the GHA build:  

https://github.com/seqeralabs/xpack-dnanexus/blob/5f213309f42d4e69d2d0cfdbc464d89e25b12a00/.github/workflows/build.yml#L14-L16

The error reported is the following 

```
  Downloading https://files.pythonhosted.org/packages/10/91/90b8d4cd611ac2aa526290ae4b4285aa5ea57ee191c63c2f3d04170d7683/cryptography-35.0.0.tar.gz (559kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zwb52wdy/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    
            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:
    
            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================
```

More details here https://github.com/seqeralabs/xpack-dnanexus/runs/4296767727?check_suite_focus=true

**Comment by pditommaso** [comment]
Solved dead18e
